---
name: apprise
services:
  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    environment: # Full list is here: https://hub.docker.com/r/caronc/apprise
      - APPRISE_STATEFUL_MODE=simple
      # - SECRET_KEY=${APPRISE_SECRET_KEY} # Applies only when stateful mode is set to `hash`
    volumes:
      - ${CONFIG_DIR}/apprise:/config
      - ${VOLUME_DIR}/apprise:/attach
    # ports:
    #   - 8000:8000
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.apprise-rtr.entrypoints=websecure
      - traefik.http.routers.apprise-rtr.rule=Host(`apprise.$FQDN`)
      - traefik.http.routers.apprise-rtr.tls=true
      ## Middlewares
      # - traefik.http.routers.apprise-rtr.middlewares=chain-no-auth@file # No Authentication
      # - traefik.http.routers.apprise-rtr.middlewares=chain-basic-auth@file # Basic Authentication
      - traefik.http.routers.apprise-rtr.middlewares=chain-oauth2-proxy@file # OAuth 2.0
      ## HTTP Services
      - traefik.http.routers.apprise-rtr.service=apprise-svc
      - traefik.http.services.apprise-svc.loadbalancer.server.port=8000

networks:
  traefik:
    name: traefik
    external: true
    #run: docker network create traefik

