---
name: joplin-server
services:
  joplin-server:
    image: etechonomy/joplin-server:latest
    container_name: joplin-server
    environment:
      - APP_BASE_URL=https://joplin.${FQDN}
      - APP_PORT=22300
      - POSTGRES_PASSWORD=${JOPLIN_DB_PASS}
      - POSTGRES_DATABASE=joplin
      - POSTGRES_USER=joplin
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=joplin-db
      - DB_CLIENT=pg
    # ports:
    #   - 22300:22300
    restart: always
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.joplin-rtr.entrypoints=websecure"
      - "traefik.http.routers.joplin-rtr.rule=Host(`joplin.$FQDN`)"
      - "traefik.http.routers.joplin-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.joplin-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.joplin-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.joplin-rtr.middlewares=chain-oauth2-proxy@file" # OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.joplin-rtr.service=joplin-svc"
      - "traefik.http.services.joplin-svc.loadbalancer.server.port=22300"

  joplin-db:
    image: postgres:16 # latest as of 1/27/2024
    container_name: joplin-db
    environment:
      - POSTGRES_PASSWORD=${JOPLIN_DB_PASS}
      - POSTGRES_USER=joplin
      - POSTGRES_DB=joplin
    # ports:
    #   - 5432:5432
    volumes:
      - ${VOLUME_DIR}/joplin-data:/var/lib/postgresql/data
    restart: always
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true
    #run: docker network create traefik
